spring:
  logging:
    level: DEBUG
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: ${pwd}
    url: jdbc:mysql://139.196.59.54:2631/yunn?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true

#nacos.config.server-addr=81.69.227.238:8848
#
#management.endpoints.web.exposure.include=*
#management.endpoint.health.show-details=always

# rabbitmqctl add_user admin admin
#rabbitmqctl set_user_tags admin administrator
#rabbitmqctl set_permissions -p / admin ".*" ".*" ".*"


test:
  val: cn,cm,cx,cz

test1:
  vals-try:
    - cn
    - cm
    - cx
    - cn
server:
  port: 9001


